CREATE USER 'test'@'%';
ALTER USER 'test'@'%'
IDENTIFIED BY 'test987' ;
GRANT Process ON *.* TO 'test'@'%';
GRANT Show databases ON *.* TO 'test'@'%';
GRANT Alter ON go_test.* TO 'test'@'%';
GRANT Create ON go_test.* TO 'test'@'%';
GRANT Create view ON go_test.* TO 'test'@'%';
GRANT Delete ON go_test.* TO 'test'@'%';
GRANT Delete history ON go_test.* TO 'test'@'%';
GRANT Drop ON go_test.* TO 'test'@'%';
GRANT Index ON go_test.* TO 'test'@'%';
GRANT Insert ON go_test.* TO 'test'@'%';
GRANT References ON go_test.* TO 'test'@'%';
GRANT Select ON go_test.* TO 'test'@'%';
GRANT Show view ON go_test.* TO 'test'@'%';
GRANT Trigger ON go_test.* TO 'test'@'%';
GRANT Update ON go_test.* TO 'test'@'%';
GRANT Grant option ON go_test.* TO 'test'@'%';
GRANT Alter routine ON go_test.* TO 'test'@'%';
GRANT Create routine ON go_test.* TO 'test'@'%';
GRANT Create temporary tables ON go_test.* TO 'test'@'%';
GRANT Execute ON go_test.* TO 'test'@'%';
GRANT Lock tables ON go_test.* TO 'test'@'%';
GRANT Alter ON test.* TO 'test'@'%';
GRANT Create ON test.* TO 'test'@'%';
GRANT Create view ON test.* TO 'test'@'%';
GRANT Delete ON test.* TO 'test'@'%';
GRANT Delete history ON test.* TO 'test'@'%';
GRANT Drop ON test.* TO 'test'@'%';
GRANT Grant option ON test.* TO 'test'@'%';
GRANT Index ON test.* TO 'test'@'%';
GRANT Insert ON test.* TO 'test'@'%';
GRANT References ON test.* TO 'test'@'%';
GRANT Select ON test.* TO 'test'@'%';
GRANT Show view ON test.* TO 'test'@'%';
GRANT Trigger ON test.* TO 'test'@'%';
GRANT Update ON test.* TO 'test'@'%';
GRANT Alter routine ON test.* TO 'test'@'%';
GRANT Create routine ON test.* TO 'test'@'%';
GRANT Create temporary tables ON test.* TO 'test'@'%';
GRANT Execute ON test.* TO 'test'@'%';
GRANT Lock tables ON test.* TO 'test'@'%';
FLUSH PRIVILEGES;
